"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import dj_database_url


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o5bt&l$iyeuj02xh3#x!bkhe05*hzj)n#mz3^q%9n2yhz0+y=&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
	'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'rest_framework',
    'polls.templatetags.app_filters',
    'gdstorage',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# Make Django work with Heroku's postgres database

#DATABASES = {}
#DATABASES['default'] =  dj_database_url.config()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/ 


STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    #'/var/www/static/',
]


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

#
# Google Drive Storage Settings
#
GOOGLE_DRIVE_STORAGE_KEY = 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCQkpGe/dmhFQv6\n38LXo8U8WG/UlGuxaKT4jj0yVeUaUrUscPQEBwho517GmWbQgCFk6K0v1y+P23NL\nVmLJxVzcBeivQ8iVPCnrtrL/IsWKR7OznSGj3Zp38o8C313JWSovw4y2DfotrvBr\nVEQyTX/R+IJh5ub2BKVIsoXnJ1WK7eStp8ZGDn7UYacVSlWfvLq/Za1FMscCqeiU\nAbQzjtA2q8I1XocpTeVlBnCHXJE/WrEqqRVbdGvSSswkdpAGjQ0SISdeulFtYFgK\nK+YMslja1gU1ZjrJF/vZOc5CDbCW8e/gwQxbOemzEsOxmT++xnFNYnahhls6IuHz\nLJfNCK/hAgMBAAECggEAa3CBR+bfFRbPEGG6KwdKTM5sTU7/uZhLAWyzjfTHjghp\nG93Veii/1zYa+PyHq+uM5bEFA8inUAGGbTaFs+04VUsO4TE+n6lWfhYIcBMnOtyO\nb60WkvDdGsboAPp+eGQLNfPdXm6Eve6EPT8ibz+o/iHww1EV0z8gliYV3PMeX1/L\nUSk6HNUD/EgtAmP33oKI66x6QLOA26kCTFD6vdKbfqJnk4FOwH2O4VA0WxafJJZQ\ny5mBa2kXnKpiTP/1nPR2tCp7mw4KU6JgAMPY9MnhjdYwFnQZTW+DUIAGyNuewzTR\nbHVUzjPdQzBgsSAc9Fkc0lHQz2gdVtDUB2dW20QdAQKBgQDb6zXPvn46KwQPRxO1\nD7b0JPZAYk6QjVufXabcY/voxvnr/eRWZftNf3eeiAw7d0+TEqWGi5dNTmWgRatL\nfZYaU834fB6FNvtJDMuNH1twuJ5R30+yYiAi9C+9tmKCx40lu77QF/q82o36j7j+\nxvy9Vuy5SckdrHDGPRiesz3/EwKBgQCoSr9Gj47AB35X1YZiUM8SYvwtZ915/qxS\nA8sp0INL7dsDWOcA/BwEDhlNkJSnjTqbDl9TlG8Zxn3m9CS8ekc+jmG7zrXXIvwq\nueh0NtPuEG6LaBA6A1j6iNkqELO3kmcJNndLt+6MGAbInq0MC7AL3wDTCLj37Kd0\nZLGV2WXPuwKBgHnZoT8x9Q6VtvIgF7NCucQclrSlw5IkQJfUdBe47mLTnLY9Pr8A\nUnVmIwkbqGtqeBStSDl8LqEOxxA+ieKR+xErTfxYCTEWfbTD+iR/M1MJd+81JBta\ncyPq2GjtHTgJCRPXKqpyHuN01SX3bDD+YBsohpFDaMOgP/wW7gVAmyExAoGAdogH\nBpywD2J3w0d6Gh8OacXcFeL05CrSlgVj/7SD9WO3ATmJonDvDpAblD0D5qsbHwDV\ndVmzkrTyEkvc3/9D1LSV86BZBQj4EOPV7Jx9Ukyyf2+xFhsrfXILeow++EmeVqfN\nCECpPHTjukPAYB6PRR0xSHH5TW2aV+lgBsoS4mcCgYEAmaGpG8ZJoL3yTRAthfmC\nATnzoOnBokYSXLSZD2bmNAfMj6QLqndqH9rDrpiiL8rkoHSSAlmoLOSrdPPWEwsj\nkEzHTbJUyztMnXHQgGBcf7fEsyLYcbe4kzfVmFF11QoavhoADJFpa9fHnqdMlKIa\nZ1zPIqRe1CPDP1EEl/zEvUQ='
GOOGLE_DRIVE_STORAGE_SERVICE_EMAIL = 'lang-it-up@sublime-lens-124715.iam.gserviceaccount.com'