# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesubtopic',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='languagetopic',
            name='topic_name_in_language',
            field=models.CharField(default='Saludo', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(choices=[('Alphabet', 'Alphabet'), ('Numbers', 'Numbers'), ('Days of the Week', 'Days of the Week'), ('Holidays', 'Holidays'), ('Seasons and Months', 'Seasons and Months'), ('Time', 'Time')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resourceitempicture',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resourceitempicture',
            name='picture_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='video_wihtout_transcript',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='video_with_transcript',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate')], default='b', max_length=1),
        ),
    ]
