# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_1',
            field=models.FileField(blank=True, default='', null=True, upload_to='vocabulary/pictures', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_2',
            field=models.FileField(blank=True, default='', null=True, upload_to='vocabulary/pictures', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_3',
            field=models.FileField(blank=True, default='', null=True, upload_to='vocabulary/pictures', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_4',
            field=models.FileField(blank=True, default='', null=True, upload_to='vocabulary/pictures', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_5',
            field=models.FileField(blank=True, default='', null=True, upload_to='vocabulary/pictures', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_6',
            field=models.FileField(blank=True, default='', null=True, upload_to='vocabulary/pictures', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='languagesubtopic',
            name='grammar_video_file',
            field=models.FileField(blank=True, null=True, upload_to='grammar video', validators=[polls.models.validate_movie_extension]),
        ),
        migrations.AlterField(
            model_name='resourcedialectitem',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='audio resources', validators=[polls.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='audio resources', validators=[polls.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='resourceitempicture',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='audio resources', validators=[polls.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='resourceitempicture',
            name='picture_url',
            field=models.FileField(blank=True, null=True, upload_to='picture resources', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='video_with_transcript',
            field=models.FileField(blank=True, null=True, upload_to='topic/video_with_transcript', validators=[polls.models.validate_movie_extension]),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='video_without_transcript',
            field=models.FileField(blank=True, null=True, upload_to='topic/video_without_transcript)', validators=[polls.models.validate_movie_extension]),
        ),
    ]
