# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160323_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='word_in_lang2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
