# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 17:27
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_exercise_learn_lecturevideo_situationalvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationalvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='situationalvideo',
            name='video_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
