# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160223_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name2',
            new_name='name_in_language',
        ),
    ]
