# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160207_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationalvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='exercise',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Language'),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Language'),
        ),
        migrations.AddField(
            model_name='situationalvideo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Language'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Language'),
        ),
    ]
