# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160223_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationalvideo',
            name='situation_description_in_language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='languagetopic',
            name='topic_name_in_language',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
