# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_language_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_in_language', models.CharField(max_length=200)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='learn',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
