# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_language_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationalvideo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='language',
        ),
    ]
