# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160216_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Language')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='languagetopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Topic'),
        ),
    ]
