# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160220_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_in_language', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('instructions_in_language', models.CharField(max_length=200)),
                ('dialect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Dialect')),
            ],
        ),
    ]
