# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160216_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationalvideo',
            name='topic',
        ),
        migrations.AddField(
            model_name='situationalvideo',
            name='language_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LanguageTopic'),
        ),
        migrations.AddField(
            model_name='situationalvideo',
            name='video_wihtout_transcript',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='situationalvideo',
            name='video_with_transcript',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
