# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('word_in_language', models.CharField(max_length=200)),
                ('pronounciation_guide_or_date', models.CharField(max_length=200)),
                ('instructions_in_language', models.CharField(max_length=200)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Resource')),
            ],
        ),
    ]
