# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160216_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSubtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=200, null=True)),
                ('language_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LanguageTopic')),
            ],
        ),
    ]
