# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_resourceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceItemPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('phrase_in_language', models.CharField(max_length=200)),
                ('picture_url', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Resource')),
            ],
        ),
        migrations.RemoveField(
            model_name='resourceitem',
            name='instructions_in_language',
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
