# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_exercise_instructions_in_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisequestion',
            name='choice_answers',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='choice_6',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
