# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160220_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(choices=[('Alphabet', 'Alphabet'), ('Numbers', 'Numbers'), ('Days of the Week', 'Days of the Week'), ('Holidays', 'Holidays'), ('Seasons and Months', 'Seasons and Months'), ('Time', 'Time')], default=0, max_length=200),
        ),
    ]
