# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_languagesubtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_topic', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('language_subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.LanguageSubtopic')),
            ],
        ),
    ]
