# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_grammarvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='choice_answers',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='language',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='topic',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='language_subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.LanguageSubtopic'),
        ),
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
