# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160223_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='word_in_language',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
