# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160216_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturevideo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='lecturevideo',
            name='topic',
        ),
        migrations.DeleteModel(
            name='LectureVideo',
        ),
    ]
