# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160223_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='pronounciation_guide_or_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
