# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_exercisequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagetopic',
            old_name='topic_name',
            new_name='topic_name_in_english',
        ),
        migrations.AddField(
            model_name='languagetopic',
            name='topic_name_in_language',
            field=models.CharField(default='Greeting', max_length=200),
        ),
    ]
