# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_exercisevocabularyquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='correct_answer',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=(1, 1), max_length=1),
        ),
    ]
