# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160225_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situationalvideo',
            old_name='video_wihtout_transcript',
            new_name='video_without_transcript',
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='correct_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=('1', '1'), max_length=1),
        ),
    ]
