# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160216_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagetopic',
            name='topic_name',
        ),
    ]
