# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20160229_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
