# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_languagetopic_topic_name_in_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisequestion',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Exercise'),
        ),
    ]
