# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20160303_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LevelLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Language')),
            ],
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_1',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_2',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_3',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_4',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_5',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_6',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='languagesubtopic',
            name='grammar_video_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_movie_extension]),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='resourceitempicture',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='resourceitempicture',
            name='picture_url',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='video_with_transcript',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_movie_extension]),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='video_without_transcript',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[polls.models.validate_movie_extension]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.LevelLanguage'),
        ),
    ]
