# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_exercisequestion_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_name',
        ),
    ]
