# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_exercise_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarvideo',
            name='language_subtopic',
        ),
        migrations.AddField(
            model_name='languagesubtopic',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='GrammarVideo',
        ),
    ]
