# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20160315_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_type',
            field=models.CharField(choices=[('ty', 'Typing'), ('tf', 'True or False'), ('dd', 'Drag and Drop'), ('mc', 'Multiple Choice')], default=('ty', 'Typing'), max_length=3),
        ),
    ]
