# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_glossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Level'),
        ),
    ]
