# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_glossary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='question_type',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='question_type',
            field=models.CharField(choices=[('ty', 'Typing'), ('tf', 'True or False'), ('dd', 'Drag and Drop'), ('mc', 'Multiple Choice')], default=('ty', 'Typing'), max_length=3),
        ),
        migrations.AlterField(
            model_name='dialect',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_1',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_2',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_3',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_4',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_5',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='exercisevocabularyquestion',
            name='choice_6',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[polls.models.validate_picture_extension]),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='correct_answers',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='situationalvideo',
            name='question_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Level'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
