# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20160320_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',), 'permissions': (('add_language', 'Can add a new language'),)},
        ),
    ]
