# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20160320_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='question_type',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='question_type',
            field=models.CharField(choices=[('ty', 'Typing'), ('tf', 'True or False'), ('dd', 'Drag and Drop'), ('mc', 'Multiple Choice')], default=('ty', 'Typing'), max_length=3),
        ),
    ]
