# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_resourceitemdialect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitemdialect',
            name='resource_item',
        ),
        migrations.DeleteModel(
            name='ResourceItemDialect',
        ),
    ]
