# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_resourcedialectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedialectitem',
            name='dialect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Dialect'),
        ),
    ]
